AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Environment:
        AWS_ACCESS_KEY_ID: your_access_key_id
        AWS_SECRET_ACCESS_KEY: your_secret_access_key
        AWS_REGION: ap-south-1
        S3_BUCKET_NAME: generatedaudiofilesbucket